blank_issues_enabled: false
contact_links:
  - name: 💬 Propose via Pull Request / المساهمة المباشرة عبر PR
    url: https://github.com/
    about: You can directly edit data/projects.json and open a Pull Request! / يمكنك تعديل ملف data/projects.json مباشرة وفتح طلب سحب
