blank_issues_enabled: false
contact_links:
  - name: 💬 Propose via Pull Request / المساهمة المباشرة عبر PR
    url: https://github.com/O2sa/arabic-opensource-directory/edit/main/data/projects.json
    about: Directly edit data/projects.json and submit a Pull Request! / يمكنك تعديل ملف data/projects.json مباشرة وفتح طلب سحب
